"""Timing visualization from JSONL records.

Single-run plots (auto-generated by TrainingTimer.close()):
    plot_run_breakdown()  -> timing_breakdown.png
    plot_timeseries()     -> timing_timeseries.png

Cross-run comparison (CLI or SLURM dependency job):
    plot_algorithm_comparison()  -> timing_comparison.png

CLI usage:
    python -m counterfactual_rl.training.smax.shared.timing.plot --manifest experiments/algo.json
"""

import argparse
import json
import os
from collections import defaultdict

import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt


def _load_records(jsonl_path):
    """Load all JSONL records from a timing file."""
    records = []
    with open(jsonl_path) as f:
        for line in f:
            line = line.strip()
            if line:
                records.append(json.loads(line))
    return records


def plot_run_breakdown(jsonl_path, save_dir=None):
    """Stacked horizontal bar of top-level component durations.

    For consequence-dqn runs, the 'update' portion is split into
    scoring sub-components vs q_update.
    """
    records = _load_records(jsonl_path)
    if not records:
        return

    save_dir = save_dir or os.path.dirname(jsonl_path)

    # Aggregate total duration per component
    totals = defaultdict(float)
    for r in records:
        totals[r['component']] += r['duration_s']

    # Determine top-level components present
    top_level = ['env', 'action', 'buffer.add', 'update', 'eval']
    # If scoring sub-components exist, split update into scoring vs q_update
    scoring_keys = [k for k in totals if k.startswith('update.scoring.')]
    has_scoring = bool(scoring_keys)

    if has_scoring:
        # Build breakdown: top-level minus update, then scoring pieces + q_update
        components = []
        times = []
        colors_list = []

        color_map = {
            'env': '#3498db',
            'action': '#1abc9c',
            'buffer.add': '#9b59b6',
            'eval': '#f39c12',
            'update.q_update': '#2ecc71',
            'update.scoring.sample': '#e74c3c',
            'update.scoring.beam': '#c0392b',
            'update.scoring.stack': '#d35400',
            'update.scoring.rollouts': '#e67e22',
            'update.scoring.metrics': '#f1c40f',
            'update.scoring.buffer_update': '#e84393',
        }

        for comp in ['env', 'action', 'buffer.add']:
            if totals.get(comp, 0) > 0:
                components.append(comp)
                times.append(totals[comp])
                colors_list.append(color_map.get(comp, '#95a5a6'))

        # Scoring sub-components
        for key in sorted(scoring_keys):
            if totals[key] > 0:
                components.append(key.replace('update.scoring.', 'scoring: '))
                times.append(totals[key])
                colors_list.append(color_map.get(key, '#95a5a6'))

        if totals.get('update.q_update', 0) > 0:
            components.append('q_update')
            times.append(totals['update.q_update'])
            colors_list.append(color_map.get('update.q_update', '#2ecc71'))

        if totals.get('eval', 0) > 0:
            components.append('eval')
            times.append(totals['eval'])
            colors_list.append(color_map.get('eval', '#f39c12'))
    else:
        color_map = {
            'env': '#3498db',
            'action': '#1abc9c',
            'buffer.add': '#9b59b6',
            'update': '#e74c3c',
            'eval': '#f39c12',
        }
        components = []
        times = []
        colors_list = []
        for comp in top_level:
            if totals.get(comp, 0) > 0:
                components.append(comp)
                times.append(totals[comp])
                colors_list.append(color_map.get(comp, '#95a5a6'))

    if not times:
        return

    total_time = totals.get('total', sum(times))

    fig, ax = plt.subplots(figsize=(12, 3))
    left = 0
    for comp, t, c in zip(components, times, colors_list):
        t_h = t / 3600
        bar = ax.barh(0, t_h, left=left, color=c, height=0.5, label=comp)
        if t / total_time > 0.04:
            pct = t / total_time * 100
            ax.text(left + t_h / 2, 0, f'{pct:.0f}%',
                    ha='center', va='center', fontsize=8, fontweight='bold',
                    color='white')
        left += t_h

    ax.set_xlabel('Time (hours)')
    ax.set_yticks([])
    total_h = total_time / 3600
    ax.set_title(f'Training Time Breakdown (total: {total_h:.2f}h)', fontweight='bold')
    ax.legend(loc='upper center', bbox_to_anchor=(0.5, -0.25), ncol=min(5, len(components)),
              fontsize=8)
    ax.grid(axis='x', alpha=0.3)

    plt.tight_layout()
    save_path = os.path.join(save_dir, 'timing_breakdown.png')
    plt.savefig(save_path, dpi=150, bbox_inches='tight', facecolor='white')
    plt.close(fig)
    print(f"Saved {save_path}")


def plot_timeseries(jsonl_path, save_dir=None):
    """Per-sampled-episode stacked area chart of component durations."""
    records = _load_records(jsonl_path)
    if not records:
        return

    save_dir = save_dir or os.path.dirname(jsonl_path)

    # Group by episode, only include records with numeric episodes
    by_episode = defaultdict(dict)
    for r in records:
        ep = r.get('episode')
        if ep is None:
            continue
        comp = r['component']
        # Only include top-level components for the timeseries
        if comp in ('env', 'action', 'buffer.add', 'update', 'eval'):
            by_episode[ep][comp] = by_episode[ep].get(comp, 0) + r['duration_s']

    if not by_episode:
        return

    episodes = sorted(by_episode.keys())
    components = ['env', 'action', 'buffer.add', 'update', 'eval']
    color_map = {
        'env': '#3498db',
        'action': '#1abc9c',
        'buffer.add': '#9b59b6',
        'update': '#e74c3c',
        'eval': '#f39c12',
    }

    # Build arrays
    data = {c: [] for c in components}
    for ep in episodes:
        for c in components:
            data[c].append(by_episode[ep].get(c, 0))

    fig, ax = plt.subplots(figsize=(12, 5))
    x = np.array(episodes)
    bottom = np.zeros(len(episodes))

    for comp in components:
        vals = np.array(data[comp])
        if vals.sum() > 0:
            ax.fill_between(x, bottom, bottom + vals, alpha=0.7,
                            label=comp, color=color_map.get(comp, '#95a5a6'))
            bottom += vals

    ax.set_xlabel('Episode')
    ax.set_ylabel('Duration (s)')
    ax.set_title('Per-Episode Timing Over Training', fontweight='bold')
    ax.legend(loc='upper left', fontsize=9)
    ax.grid(alpha=0.3)

    plt.tight_layout()
    save_path = os.path.join(save_dir, 'timing_timeseries.png')
    plt.savefig(save_path, dpi=150, bbox_inches='tight', facecolor='white')
    plt.close(fig)
    print(f"Saved {save_path}")


def plot_algorithm_comparison(manifest_path, save_path=None):
    """Compare timing across algorithms from an experiment manifest.

    Reads manifest JSON (job_id -> config overrides), loads timing.jsonl
    from each run directory, generates a 2-panel comparison plot.
    """
    with open(manifest_path) as f:
        manifest = json.load(f)

    # Group runs by algorithm
    algo_groups = defaultdict(list)  # algo_label -> [(job_id, overrides, records)]
    for job_id, overrides in manifest.items():
        algo = overrides.get('algorithm', 'dqn')
        label = {
            'consequence-dqn': 'Consequence DQN',
            'dqn': 'DQN + PER',
            'dqn-uniform': 'DQN (uniform)',
        }.get(algo, algo)

        run_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'runs', job_id)
        jsonl_path = os.path.join(run_dir, 'timing.jsonl')
        if not os.path.exists(jsonl_path):
            print(f"Warning: {jsonl_path} not found, skipping job {job_id}")
            continue

        records = _load_records(jsonl_path)
        algo_groups[label].append((job_id, overrides, records))

    if not algo_groups:
        print("No timing data found for any runs.")
        return

    # Compute per-algorithm stats
    algo_data = {}
    for label, runs in algo_groups.items():
        wall_times = []
        scoring_times = []
        scoring_components = defaultdict(float)
        n_with_scoring = 0

        for job_id, overrides, records in runs:
            totals = defaultdict(float)
            for r in records:
                totals[r['component']] += r['duration_s']

            wt = totals.get('total', 0)
            if wt > 0:
                wall_times.append(wt)

            # Check for scoring sub-components
            scoring_keys = [k for k in totals if k.startswith('update.scoring.')]
            if scoring_keys:
                scoring_total = sum(totals[k] for k in scoring_keys)
                scoring_times.append(scoring_total)
                n_with_scoring += 1
                for k in scoring_keys:
                    comp = k.replace('update.scoring.', '')
                    scoring_components[comp] += totals[k]

        if not wall_times:
            continue

        # Average scoring components
        if n_with_scoring > 0:
            avg_components = {k: v / n_with_scoring
                              for k, v in scoring_components.items()}
        else:
            avg_components = None

        algo_data[label] = {
            'wall_times': wall_times,
            'scoring_totals': scoring_times or None,
            'scoring_components': avg_components,
            'n_episodes': runs[0][1].get('n_episodes', '?'),
            'scenario': runs[0][1].get('scenario', '?'),
        }

    if not algo_data:
        print("No wall time data to plot.")
        return

    # Sort by mean wall time
    algo_order = sorted(algo_data.keys(),
                        key=lambda a: np.mean(algo_data[a]['wall_times']))

    fig, axes = plt.subplots(1, 2, figsize=(14, 6),
                             gridspec_kw={'width_ratios': [1, 1.3]})

    # --- Left panel: bar chart ---
    ax1 = axes[0]
    x = np.arange(len(algo_order))

    training_h = []
    scoring_h = []
    total_h = []

    for algo in algo_order:
        d = algo_data[algo]
        mean_wall = np.mean(d['wall_times'])
        mean_scoring = np.mean(d['scoring_totals']) if d['scoring_totals'] else 0
        mean_training = mean_wall - mean_scoring
        training_h.append(mean_training / 3600)
        scoring_h.append(mean_scoring / 3600)
        total_h.append(mean_wall / 3600)

    ax1.bar(x, training_h, 0.5, label='Training', color='#3498db')
    ax1.bar(x, scoring_h, 0.5, bottom=training_h,
            label='Scoring overhead', color='#e74c3c')

    for i, total in enumerate(total_h):
        ax1.text(i, total + 0.05, f'{total:.2f}h',
                 ha='center', va='bottom', fontweight='bold', fontsize=11)

    fastest = total_h[0]
    for i in range(1, len(total_h)):
        slowdown = total_h[i] / fastest
        ax1.annotate(
            f'{slowdown:.1f}x slower', xy=(i, total_h[i]),
            xytext=(i - 0.3, total_h[i] + max(total_h) * 0.08),
            fontsize=9, color='#e74c3c',
            arrowprops=dict(arrowstyle='->', color='#e74c3c', lw=1.5),
        )

    n_seeds = len(algo_data[algo_order[0]]['wall_times'])
    n_episodes = algo_data[algo_order[0]].get('n_episodes', '?')
    scenario = algo_data[algo_order[0]].get('scenario', '?')

    ax1.set_ylabel('Wall Time (hours)', fontsize=11)
    ax1.set_title(
        f'Training Time by Algorithm\n({n_episodes} episodes, {scenario}, '
        f'{n_seeds} seeds avg)',
        fontsize=13, fontweight='bold',
    )
    ax1.set_xticks(x)
    ax1.set_xticklabels(algo_order, fontsize=10)
    ax1.legend(fontsize=10)
    ax1.grid(axis='y', alpha=0.3)
    ax1.set_ylim(0, max(total_h) * 1.2)

    # --- Right panel: breakdown of slowest algorithm ---
    ax2 = axes[1]
    slowest = algo_order[-1]
    d = algo_data[slowest]
    mean_wall = np.mean(d['wall_times'])

    if d['scoring_components']:
        comps = d['scoring_components']
        scoring_total = sum(comps.values())
        training_time = mean_wall - scoring_total

        labels = ['Training\n(non-scoring)', 'Rollouts\n(GPU)', 'Metrics\n(CPU)',
                  'Stack\n(pytree)', 'Other scoring']
        times = [
            training_time,
            comps.get('rollouts', 0),
            comps.get('metrics', 0),
            comps.get('stack', 0),
            comps.get('beam', 0) + comps.get('sample', 0) + comps.get('buffer_update', 0),
        ]
        colors = ['#3498db', '#e74c3c', '#f39c12', '#2ecc71', '#9b59b6']
    else:
        mean_scoring = np.mean(d['scoring_totals']) if d['scoring_totals'] else 0
        labels = ['Training\n(non-scoring)', 'Scoring\n(total)']
        times = [mean_wall - mean_scoring, mean_scoring]
        colors = ['#3498db', '#e74c3c']

    ax2.set_title(f'{slowest}: Where Time Goes', fontsize=13, fontweight='bold')

    left = 0
    for label, t, c in zip(labels, times, colors):
        t_h = t / 3600
        ax2.barh(0, t_h, left=left, color=c, height=0.5, label=label)
        if t_h > 0.05:
            pct = t / mean_wall * 100
            text_color = 'white' if c != '#f39c12' else 'black'
            ax2.text(left + t_h / 2, 0, f'{pct:.0f}%\n({t_h:.2f}h)',
                     ha='center', va='center', fontsize=8,
                     fontweight='bold', color=text_color)
        left += t_h

    ax2.set_xlabel('Time (hours)', fontsize=11)
    ax2.set_yticks([])
    ax2.legend(loc='upper center', bbox_to_anchor=(0.5, -0.15),
               ncol=3, fontsize=9)
    ax2.grid(axis='x', alpha=0.3)

    plt.tight_layout()

    if save_path is None:
        manifest_dir = os.path.dirname(os.path.abspath(manifest_path))
        base = os.path.splitext(os.path.basename(manifest_path))[0]
        save_path = os.path.join(manifest_dir, f'{base}_timing_comparison.png')

    plt.savefig(save_path, dpi=150, bbox_inches='tight', facecolor='white')
    plt.close(fig)
    print(f"Saved {save_path}")


def main():
    parser = argparse.ArgumentParser(
        description='Generate timing comparison plot from experiment manifest')
    parser.add_argument('--manifest', required=True,
                        help='Manifest JSON file from run_experiments.py')
    parser.add_argument('-o', '--output', default=None,
                        help='Output PNG path')
    args = parser.parse_args()

    plot_algorithm_comparison(args.manifest, save_path=args.output)


if __name__ == '__main__':
    main()
