DEFAULT_CONFIG = {
    'map_name': '8x8',
    'is_slippery': True,
    'algorithm': 'consequence-dqn',
    'gamma': 0.99,
    'epsilon_start': 1.0,
    'epsilon_end': 0.05,
    'epsilon_decay_episodes': 10000,
    'alpha': 0.001,
    'batch_size': 32,
    'buffer_capacity': 100000,
    'target_update_freq': 200,
    'n_steps_per_update': 4,
    'hidden_dim': 64,
    'n_layers': 2,
    'n_episodes': 30000,
    'eval_interval': 300,
    'eval_episodes': 50,
    'save_every': 500,
    'n_checkpoints': 100,
    'seed': 0,
    'PER_parameters': {'eps': 0.01, 'beta': 0.25, 'maximum_priority': 1.0},
    # Consequence-weighted PER
    'mu': 0.5,
    'priority_mixing': 'additive',
    'mu_c': 1.0,
    'mu_delta': 1.0,
    'score_interval': 100,
    'n_score_sample': 128,
    'consequence_metric': 'jensen_shannon',
    'consequence_aggregation': 'weighted_mean',
    'cf_horizon': 10,
    'cf_n_rollouts': 20,
    'cf_gamma': 0.99,
}
